
SELECT * FROM tbcliente WHERE DATA_NASCIMENTO <= '1995-01-13';
SELECT * FROM tbcliente WHERE YEAR(DATA_NASCIMENTO) = 1995;
SELECT * FROM tbcliente WHERE MONTH(DATA_NASCIMENTO) = 10;

SELECT * FROM tbproduto ;
SELECT * FROM tbproduto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;
SELECT * FROM tbproduto WHERE PRECO_LISTA >= 16.007;
SELECT * FROM tbproduto WHERE PRECO_LISTA <= 16.009;
SELECT * FROM tbproduto WHERE PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;
SELECT * FROM tbcliente WHERE IDADE >= 18 AND IDADE <= 22 AND SEXO ='M';
SELECT * FROM tbcliente WHERE CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins';
SELECT * FROM tbcliente WHERE (IDADE >= 18 AND IDADE <= 22 AND SEXO ='M') OR (CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins');

SELECT NOME FROM tbtabela_de_vendedores WHERE NOME = 'Cláudia Morais';

SELECT * FROM tbtabela_de_vendedores WHERE PERCENTUAL_COMISSAO > 0.10;

SELECT * FROM tbtabela_de_vendedores WHERE YEAR(DATA_ADMISSAO) >= 2016;

SELECT * FROM tbtabela_de_vendedores WHERE (YEAR(DATA_ADMISSAO) >= 2016) AND (FÉRIAS = '1');
