algoritmo "ConteAteDez"
var
     contador: Inteiro
inicio
     contador <- 0
     Enquanto (Contador <=10) faca
              Escreval (contador)
              contador <- contador + 1
     Fimenquanto
              Escreval ("Terminei de contar")
              
     contador <- 10
     Enquanto (Contador >=0) faca
              Escreval (contador)
              contador <- contador - 1
     Fimenquanto
              Escreval ("Terminei a contagem regressiva!")
fimalgoritmo