Algoritmo "Creuza04"

Var
          emp, parcelas, valorParcela, juros,valorTotal: Real


Inicio

       Escreva ("Qual o valor do empréstimo? ")
       Leia (emp)
       Escreva ("Quantas parcelas? ")
       Leia (parcelas)
       juros <- emp*20/100
       valorTotal <- juros+emp
       valorParcela <- valortotal/parcelas
       Escreval ("O Valor total do empréstimo é de R$ ", ValorTotal)
       Escreva ("O Valor de cada parcela é de R$ ", valorParcela:5:2)
       

        
Fimalgoritmo